# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8acbe1bb698616c06e42216e4723b725eaf0553c81fc046ee8849816b2196c614ed78e11554dcf5825ab2b31ab617520b09ed1727bbb0c187871c8b243e80da3

test:
  secret_key_base: c106c7bc4607b7d967059667d63c5b5487738321de880695bdc6236ebb6cc3d2aa84781a146f80b1e6212ddac2e7e3afda92e565b352d4f286b6dc66f944012d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
